services:
  server:
    image: server:0.0.1
    container_name: main-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    container_name: server-db
    restart: unless-stopped
    volumes:
      - ./infrastructure/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=grade_book_user
      - POSTGRES_PASSWORD=grade_book_password
      - POSTGRES_DB=grade_book_db